// File generated by FlutterFire CLI.
// This is a template file - you need to run `flutterfire configure` to generate the actual file

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example code:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5spQ60V_ycNOXyJOWl4TI8zJdfPYu6J4',
    appId: '1:316548551513:web:42e69b5bd4a12c52def248',
    messagingSenderId: '316548551513',
    projectId: 'parkinn',
    authDomain: 'parkinn.firebaseapp.com',
    storageBucket: 'parkinn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRRTMus_3pPpkNqkqhVPaL_g4WibpTw5o',
    appId: '1:316548551513:android:c180270120fd2ce1def248',
    messagingSenderId: '316548551513',
    projectId: 'parkinn',
    storageBucket: 'parkinn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJbhr8TMqaaj7h8yKxnkUZzrQu3jKljM',
    appId: '1:316548551513:ios:4fe31e2c5a0b82e0def248',
    messagingSenderId: '316548551513',
    projectId: 'parkinn',
    storageBucket: 'parkinn.firebasestorage.app',
    iosBundleId: 'com.example.washinn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTJbhr8TMqaaj7h8yKxnkUZzrQu3jKljM',
    appId: '1:316548551513:ios:4fe31e2c5a0b82e0def248',
    messagingSenderId: '316548551513',
    projectId: 'parkinn',
    storageBucket: 'parkinn.firebasestorage.app',
    iosBundleId: 'com.example.washinn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5spQ60V_ycNOXyJOWl4TI8zJdfPYu6J4',
    appId: '1:316548551513:web:534c16cb69826221def248',
    messagingSenderId: '316548551513',
    projectId: 'parkinn',
    authDomain: 'parkinn.firebaseapp.com',
    storageBucket: 'parkinn.firebasestorage.app',
  );

}